apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookstore-application
  namespace: open-cluster-management
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchLabels:
      app: bookstore
