apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-bookstore
  namespace: open-cluster-management
placementRef:
  name: all-clusters
  kind: PlacementRule
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: bookstore-subscription
    kind: Subscription
    apiGroup: apps.open-cluster-management.io
