# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookstore-mysql-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3306
  selector:
    app: bookstore-mysql
