apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-controller
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocm-controller
  template:
    metadata:
      labels:
        app: ocm-controller
    spec:
      containers:
      - name: ocm-controller
        image: quay.io/open-cluster-management/ocm-controller:release-2.4
        ports:
        - containerPort: 443
