apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume-1
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume-1
          configMap:
            name: nginx-html-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Kubernetes Nginx!</title>
    </head>
    <body>
      <h1>Hello from Nginx <b>Instance 1</b> running on Kubernetes!</h1>
      <p>This is a basic example of hosting an Nginx server.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx

